import Foundation
import CoreGraphics
import AppKit
import ApplicationServices
import Combine

/// A single observed input event, for trigger matching and the diagnostics
/// panel.
struct DetectedInput: Identifiable, Equatable {
    enum Kind: Equatable {
        case mouseDown(button: Int)
        case mouseUp(button: Int)
        case keyDown(keyCode: Int, modifiers: KeyModifiers)
        case keyUp(keyCode: Int, modifiers: KeyModifiers)
    }

    let id = UUID()
    var kind: Kind
    var timestamp: Date
    /// True when the event was generated by this app's own click engine.
    var isSynthetic: Bool

    var eventTypeName: String {
        switch kind {
        case .mouseDown: return "Mouse Down"
        case .mouseUp: return "Mouse Up"
        case .keyDown: return "Key Down"
        case .keyUp: return "Key Up"
        }
    }

    var detailText: String {
        switch kind {
        case .mouseDown(let b), .mouseUp(let b):
            return "\(MouseButton(buttonNumber: b).displayName) — button number \(b)"
        case .keyDown(let code, let mods), .keyUp(let code, let mods):
            let key = KeyCodeNames.name(for: code)
            return mods.rawValue == 0 ? "\(key) (code \(code))" : "\(mods.displaySymbols) \(key) (code \(code))"
        }
    }

    /// The trigger this event would assign, if any.
    var asTrigger: TriggerInput? {
        switch kind {
        case .mouseDown(let b): return .mouseButton(number: b)
        case .keyDown(let code, let mods): return .keyboard(keyCode: code, modifiers: mods)
        default: return nil
        }
    }
}

/// What the tap should do while a capture flow is active.
enum CaptureMode: Equatable {
    /// Input-detection mode: report the next pressed button/key so the user
    /// can assign it and see its raw button number.
    case detectInput
    /// Coordinate capture: report the location of the next physical click.
    case capturePoint
}

/// Snapshot of everything the tap callback needs to make synchronous
/// decisions. Swapped atomically under a lock whenever configuration
/// changes, so the hot path never touches main-thread state.
struct MonitorConfiguration: Equatable {
    var trigger: TriggerInput = .none
    var behavior: InputBehavior = .passThrough
    var emergencyStop: KeyboardShortcut = .defaultEmergencyStop
    var captureMode: CaptureMode? = nil
    /// Feed all real events to the diagnostics panel.
    var diagnosticsEnabled: Bool = false
}

/// Global keyboard + mouse monitoring via a CGEventTap.
///
/// The tap runs on its own thread with its own run loop so a busy main
/// thread can never stall event delivery (a stalled tap gets disabled by the
/// system). When Accessibility permission allows, the tap is created as an
/// *active* tap that can suppress matching events; otherwise it falls back
/// to listen-only and suppression is reported as unavailable.
final class GlobalInputMonitor: ObservableObject {
    // High-level callbacks, delivered on the main queue unless noted.
    var onTriggerDown: (() -> Void)?
    var onTriggerUp: (() -> Void)?
    /// Fired on the MAIN queue for UI/state updates (disarm, sounds).
    var onEmergencyStop: (() -> Void)?
    /// Fired SYNCHRONOUSLY on the event-tap thread so the engine can be
    /// stopped with zero main-thread dependency — the emergency stop must
    /// work even if the main thread is stalled (heavy render, a modal, or a
    /// full-screen game holding the run loop). The handler must be
    /// thread-safe and fast.
    var onEmergencyStopImmediate: (() -> Void)?
    var onDetectedInput: ((DetectedInput) -> Void)?
    var onCapturedInput: ((DetectedInput) -> Void)?
    var onCapturedPoint: ((CGPoint) -> Void)?

    @Published private(set) var isMonitoring = false
    /// True when the tap is an active tap that can swallow events. Mirrored
    /// into an atomic flag (`suppressionEnabled`) for the tap thread.
    @Published private(set) var canSuppress = false
    /// Lock-guarded mirror of `canSuppress`, read on the tap thread.
    private let suppressLock = NSLock()
    private var suppressionEnabled = false

    private let configLock = NSLock()
    private var _configuration = MonitorConfiguration()

    var configuration: MonitorConfiguration {
        get {
            configLock.lock(); defer { configLock.unlock() }
            return _configuration
        }
        set {
            configLock.lock()
            _configuration = newValue
            configLock.unlock()
        }
    }

    private var eventTap: CFMachPort?
    private var runLoopSource: CFRunLoopSource?
    private var tapThread: Thread?
    private var tapRunLoop: CFRunLoop?
    private let startStopLock = NSLock()

    deinit {
        stop()
    }

    /// Creates and starts the event tap. Returns false when the tap could
    /// not be created (usually missing Accessibility permission).
    @discardableResult
    func start() -> Bool {
        startStopLock.lock()
        defer { startStopLock.unlock() }
        guard eventTap == nil else { return true } // never create a duplicate tap

        let mask: CGEventMask =
            (1 << CGEventType.leftMouseDown.rawValue) |
            (1 << CGEventType.leftMouseUp.rawValue) |
            (1 << CGEventType.rightMouseDown.rawValue) |
            (1 << CGEventType.rightMouseUp.rawValue) |
            (1 << CGEventType.otherMouseDown.rawValue) |
            (1 << CGEventType.otherMouseUp.rawValue) |
            (1 << CGEventType.keyDown.rawValue) |
            (1 << CGEventType.keyUp.rawValue)

        let refcon = Unmanaged.passUnretained(self).toOpaque()

        // Prefer an active (default) tap so trigger events can be
        // suppressed. Fall back to listen-only if that fails.
        var tap = CGEvent.tapCreate(
            tap: .cgSessionEventTap,
            place: .headInsertEventTap,
            options: .defaultTap,
            eventsOfInterest: mask,
            callback: inputMonitorTapCallback,
            userInfo: refcon)
        var suppressCapable = tap != nil

        if tap == nil {
            tap = CGEvent.tapCreate(
                tap: .cgSessionEventTap,
                place: .headInsertEventTap,
                options: .listenOnly,
                eventsOfInterest: mask,
                callback: inputMonitorTapCallback,
                userInfo: refcon)
            suppressCapable = false
        }

        guard let createdTap = tap else {
            setSuppression(false)
            DispatchQueue.main.async {
                self.isMonitoring = false
                self.canSuppress = false
            }
            return false
        }

        eventTap = createdTap
        let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, createdTap, 0)
        runLoopSource = source

        // Dedicated thread + run loop for the tap.
        let thread = Thread { [weak self] in
            guard let self, let source = self.runLoopSource else { return }
            self.tapRunLoop = CFRunLoopGetCurrent()
            CFRunLoopAddSource(CFRunLoopGetCurrent(), source, .commonModes)
            CGEvent.tapEnable(tap: createdTap, enable: true)
            CFRunLoopRun() // exits when the source is removed by stop()
        }
        thread.name = "com.autoclicker.event-tap"
        thread.qualityOfService = .userInteractive
        tapThread = thread
        thread.start()

        setSuppression(suppressCapable)
        DispatchQueue.main.async {
            self.isMonitoring = true
            self.canSuppress = suppressCapable
        }
        return true
    }

    private func setSuppression(_ value: Bool) {
        suppressLock.lock()
        suppressionEnabled = value
        suppressLock.unlock()
    }

    /// Tears the tap down completely. Idempotent.
    func stop() {
        startStopLock.lock()
        defer { startStopLock.unlock() }
        guard let tap = eventTap else { return }
        CGEvent.tapEnable(tap: tap, enable: false)
        if let source = runLoopSource, let runLoop = tapRunLoop {
            CFRunLoopRemoveSource(runLoop, source, .commonModes)
            CFRunLoopStop(runLoop)
        }
        CFMachPortInvalidate(tap)
        eventTap = nil
        runLoopSource = nil
        tapRunLoop = nil
        tapThread = nil
        setSuppression(false)
        DispatchQueue.main.async {
            self.isMonitoring = false
            self.canSuppress = false
        }
    }

    /// Restart after a permission change (e.g. Accessibility toggled).
    func restart() {
        stop()
        start()
    }

    /// Verifies the tap is still alive and listening, repairing it if not.
    ///
    /// macOS can disable or invalidate an event tap behind our back — most
    /// commonly across sleep/wake, but also on fast user switching or if the
    /// callback ever overruns its time budget. When that happens the app
    /// silently stops seeing input (triggers just "stop working") because a
    /// dead tap delivers no events, not even the disable notification. This
    /// re-enables a merely-disabled tap, and fully rebuilds an invalid one.
    /// Safe to call repeatedly from the main thread.
    func verifyAlive() {
        startStopLock.lock()
        let tap = eventTap
        startStopLock.unlock()

        guard let tap else {
            // No tap at all — try to (re)create it if we're allowed to.
            if AXIsProcessTrusted() { start() }
            return
        }
        if !CFMachPortIsValid(tap) {
            restart()
            return
        }
        if !CGEvent.tapIsEnabled(tap: tap) {
            CGEvent.tapEnable(tap: tap, enable: true)
            // If it refuses to re-enable, rebuild from scratch.
            if !CGEvent.tapIsEnabled(tap: tap) { restart() }
        }
    }

    // MARK: - Tap callback core (runs on the tap thread)

    /// Decides what to do with one event. Returns true when the event should
    /// be suppressed (only honored for active taps).
    fileprivate func handle(type: CGEventType, event: CGEvent) -> Bool {
        // Re-enable the tap if the system disabled it (timeout or user input
        // during login shielding). Without this the app silently stops
        // seeing input.
        if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
            if let tap = eventTap { CGEvent.tapEnable(tap: tap, enable: true) }
            return false
        }

        // Ignore our own synthetic events entirely — this is the guard
        // against self-triggering loops. The click engine tags every event
        // it posts (see CGEventPoster.syntheticEventTag).
        let isSynthetic = event.getIntegerValueField(.eventSourceUserData) == CGEventPoster.syntheticEventTag

        let config = configuration
        guard let input = Self.classify(type: type, event: event, synthetic: isSynthetic) else {
            return false
        }

        if config.diagnosticsEnabled {
            dispatchMain { self.onDetectedInput?(input) }
        }
        if isSynthetic { return false }

        // 1. Emergency stop — absolute priority over everything else.
        if case .keyDown(let code, let mods) = input.kind,
           config.emergencyStop.matches(keyCode: code, modifiers: mods) {
            // Stop the engine synchronously on this thread first — no
            // dependency on the main thread being responsive — then update
            // UI/state on main.
            onEmergencyStopImmediate?()
            dispatchMain { self.onEmergencyStop?() }
            return canSuppressNow()
        }

        // 2. Capture flows.
        if let capture = config.captureMode {
            switch capture {
            case .detectInput:
                switch input.kind {
                case .mouseDown, .keyDown:
                    dispatchMain { self.onCapturedInput?(input) }
                    // Swallow non-left presses so assigning e.g. Mouse
                    // Button 4 doesn't also act in the app underneath. Left
                    // clicks pass through so the user can still operate UI.
                    if case .mouseDown(button: 0) = input.kind { return false }
                    return canSuppressNow()
                default:
                    return false
                }
            case .capturePoint:
                if case .mouseDown = input.kind {
                    let location = event.location // CG global coordinates
                    dispatchMain { self.onCapturedPoint?(location) }
                    return canSuppressNow()
                }
                return false
            }
        }

        // 3. Trigger matching.
        switch (config.trigger, input.kind) {
        case (.mouseButton(let assigned), .mouseDown(let pressed)) where assigned == pressed:
            dispatchMain { self.onTriggerDown?() }
            return config.behavior.wantsSuppression && canSuppressNow()
        case (.mouseButton(let assigned), .mouseUp(let released)) where assigned == released:
            dispatchMain { self.onTriggerUp?() }
            return config.behavior.wantsSuppression && canSuppressNow()
        case (.keyboard(let keyCode, let modifiers), .keyDown(let code, let mods))
            where keyCode == code && modifiers == mods:
            // Ignore key-repeat so hold mode doesn't restart on autorepeat.
            if event.getIntegerValueField(.keyboardEventAutorepeat) != 0 {
                return config.behavior.wantsSuppression && canSuppressNow()
            }
            dispatchMain { self.onTriggerDown?() }
            return config.behavior.wantsSuppression && canSuppressNow()
        case (.keyboard(let keyCode, _), .keyUp(let code, _)) where keyCode == code:
            // Match key-up on key code alone: the user may release the
            // modifiers before the key itself.
            dispatchMain { self.onTriggerUp?() }
            return config.behavior.wantsSuppression && canSuppressNow()
        default:
            return false
        }
    }

    private func canSuppressNow() -> Bool {
        suppressLock.lock()
        defer { suppressLock.unlock() }
        return suppressionEnabled
    }

    private func dispatchMain(_ work: @escaping () -> Void) {
        DispatchQueue.main.async(execute: work)
    }

    private static func classify(type: CGEventType, event: CGEvent, synthetic: Bool) -> DetectedInput? {
        let now = Date()
        switch type {
        case .leftMouseDown:
            return DetectedInput(kind: .mouseDown(button: 0), timestamp: now, isSynthetic: synthetic)
        case .leftMouseUp:
            return DetectedInput(kind: .mouseUp(button: 0), timestamp: now, isSynthetic: synthetic)
        case .rightMouseDown:
            return DetectedInput(kind: .mouseDown(button: 1), timestamp: now, isSynthetic: synthetic)
        case .rightMouseUp:
            return DetectedInput(kind: .mouseUp(button: 1), timestamp: now, isSynthetic: synthetic)
        case .otherMouseDown, .otherMouseUp:
            let number = Int(event.getIntegerValueField(.mouseEventButtonNumber))
            let kind: DetectedInput.Kind = type == .otherMouseDown
                ? .mouseDown(button: number) : .mouseUp(button: number)
            return DetectedInput(kind: kind, timestamp: now, isSynthetic: synthetic)
        case .keyDown, .keyUp:
            let keyCode = Int(event.getIntegerValueField(.keyboardEventKeycode))
            let modifiers = KeyModifiers(cgFlags: event.flags)
            let kind: DetectedInput.Kind = type == .keyDown
                ? .keyDown(keyCode: keyCode, modifiers: modifiers)
                : .keyUp(keyCode: keyCode, modifiers: modifiers)
            return DetectedInput(kind: kind, timestamp: now, isSynthetic: synthetic)
        default:
            return nil
        }
    }
}

/// C-style tap callback: forwards into the monitor instance held in refcon.
/// Returning nil swallows the event (active taps only).
private func inputMonitorTapCallback(
    proxy: CGEventTapProxy,
    type: CGEventType,
    event: CGEvent,
    refcon: UnsafeMutableRawPointer?
) -> Unmanaged<CGEvent>? {
    guard let refcon else { return Unmanaged.passUnretained(event) }
    let monitor = Unmanaged<GlobalInputMonitor>.fromOpaque(refcon).takeUnretainedValue()
    let suppress = monitor.handle(type: type, event: event)
    return suppress ? nil : Unmanaged.passUnretained(event)
}

extension KeyModifiers {
    /// Maps CGEventFlags onto the model layer's Codable modifier set.
    init(cgFlags: CGEventFlags) {
        var mods: KeyModifiers = []
        if cgFlags.contains(.maskCommand) { mods.insert(.command) }
        if cgFlags.contains(.maskShift) { mods.insert(.shift) }
        if cgFlags.contains(.maskAlternate) { mods.insert(.option) }
        if cgFlags.contains(.maskControl) { mods.insert(.control) }
        self = mods
    }
}
